name: "Paragon Admin Experience"
description: "This recipe sets up the Layout Builder for the Paragon project"
type: "Content"
recipes:
install:
  - gin
  - gin_lb
  - gin_lb_plus
  - gin_toolbar
  - inline_block_title_automatic
  - kinetic_extras
  - navigation
  - layout_builder
  - layout_builder_browser
  - layout_builder_operation_link
  - layout_discovery
  - section_library
config:
  strict: false
  import:
    gin: "*"
    navigation: "*"
  actions:
    block.block.gin_account_menu:
      setStatus: false
    block.block.gin_main_menu:
      setStatus: false
    block.block.gin_powered:
      setStatus: false
    block.block.gin_search_form_wide:
      setStatus: false
    block.block.gin_search_form_narrow:
      setStatus: false
    block.block.gin_syndicate:
      setStatus: false
    block.block.gin_site_branding:
      setStatus: false
    gin_lb.settings:
      simpleConfigUpdate:
        hide_discard_button: false
    system.theme:
      simpleConfigUpdate:
        admin: gin
